### ISSUE TITLE
Anonymous sub class in PageFind.java

### ISSUE THREAD

**Issue by cmsc495-fall2016** [cmsc495-fall2016/cmsc495-fall2016.github.io#11]
Remove anonymous class from constructor in PageFind.java and utilize the actionPerformed method.

Example modifications could be:
<button>.setActionCommand("<Command>") 
expand on actionPerformed: if event.getActionCommand() == "<Command>"{<code in actions>}

**Comment by ahowell82** [comment]
resolved in [b37599e58038b18ef78920846c4520f511769e24]
