### ISSUE TITLE
Export is not working

### ISSUE THREAD

**Issue by eliotpearson** [cmsc495-fall2016/cmsc495-fall2016.github.io#17]
I tried to export with the latest build and selection window didn't allow it.

![screen shot 2016-10-08 at 6 21 01 am](https://cloud.githubusercontent.com/assets/1199317/19212467/beaa2b54-8d1f-11e6-9189-6b2fba405f80.png)

**Comment by ahowell82** [comment]
Export algorithm needs to determine the file output name based upon the recipe name and create the file & the user needs to select the directory to output to

**Comment by ahowell82** [comment]
Change to select directory and create the file for the user

**Comment by ahowell82** [comment]
Can you test this one & reply

**Comment by eliotpearson** [comment]
Looks good in the latest.  I'm closing this issue.
