### ISSUE TITLE
Error in cmsc495.test_classes.Recipe_Test.java 

### ISSUE THREAD

**Issue by ahowell82** [cmsc495-fall2016/cmsc495-fall2016.github.io#4]
If there is no recipe.db the updateRecipeTable() throws a SQLExecption if you execute the All_Test.java.main()

Suggest testing if the recipe.db exists prior to calling recipeDelete.clearRecipeTable()

**Comment by jhelphenstine** [comment]
I'm on it

**Comment by jhelphenstine** [comment]
see commit: 1efb73cdb733f651e0565df68e75843b3f0e8b45
