### ISSUE TITLE
PageFind.java lists the wrong package

### ISSUE THREAD

**Issue by cmsc495-fall2016** [cmsc495-fall2016/cmsc495-fall2016.github.io#8]
Update the package & re-commit

**Comment by eliotpearson** [comment]
@ahowell82 I see PageFind.java is in sharkbread.ui.  Should it move to someplace else?

**Comment by ahowell82** [comment]
It was committed listing cmsc495.ui, it has been fixed.

**Comment by eliotpearson** [comment]
Great.  I'm closing the issue.
